-- CreateTable
CREATE TABLE "custom_orders" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "clientId" TEXT NOT NULL,
    "escortId" TEXT NOT NULL,
    "type" TEXT NOT NULL,
    "title" TEXT NOT NULL,
    "description" TEXT NOT NULL,
    "requirements" JSONB,
    "proposedPrice" INTEGER,
    "finalPrice" INTEGER,
    "priority" TEXT NOT NULL DEFAULT 'STANDARD',
    "estimatedDelivery" DATETIME,
    "status" TEXT NOT NULL DEFAULT 'PENDING',
    "escortNotes" TEXT,
    "clientFeedback" TEXT,
    "rating" INTEGER,
    "deliveredFiles" JSONB,
    "previewFiles" JSONB,
    "paidAt" DATETIME,
    "deliveredAt" DATETIME,
    "conversationId" TEXT,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" DATETIME NOT NULL,
    CONSTRAINT "custom_orders_escortId_fkey" FOREIGN KEY ("escortId") REFERENCES "users" ("id") ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT "custom_orders_clientId_fkey" FOREIGN KEY ("clientId") REFERENCES "users" ("id") ON DELETE CASCADE ON UPDATE CASCADE
);

-- RedefineTables
PRAGMA defer_foreign_keys=ON;
PRAGMA foreign_keys=OFF;
CREATE TABLE "new_escort_profiles" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "userId" TEXT NOT NULL,
    "firstName" TEXT NOT NULL,
    "stageName" TEXT NOT NULL,
    "dateOfBirth" DATETIME NOT NULL,
    "nationality" TEXT NOT NULL,
    "languages" TEXT NOT NULL,
    "city" TEXT NOT NULL,
    "workingArea" TEXT NOT NULL,
    "description" TEXT NOT NULL,
    "services" TEXT NOT NULL,
    "rates" TEXT NOT NULL,
    "availability" TEXT NOT NULL,
    "profilePhoto" TEXT,
    "galleryPhotos" TEXT NOT NULL,
    "videos" TEXT NOT NULL,
    "status" TEXT NOT NULL DEFAULT 'PENDING',
    "verificationData" JSONB,
    "isVerifiedBadge" BOOLEAN NOT NULL DEFAULT false,
    "profileCompleted" BOOLEAN NOT NULL DEFAULT false,
    "photosCount" INTEGER NOT NULL DEFAULT 0,
    "videosCount" INTEGER NOT NULL DEFAULT 0,
    "hasProfilePhoto" BOOLEAN NOT NULL DEFAULT false,
    "views" INTEGER NOT NULL DEFAULT 0,
    "likes" INTEGER NOT NULL DEFAULT 0,
    "rating" REAL NOT NULL DEFAULT 0,
    "reviewCount" INTEGER NOT NULL DEFAULT 0,
    "telegramChatId" TEXT,
    "telegramUsername" TEXT,
    "telegramConnected" BOOLEAN NOT NULL DEFAULT false,
    "telegramEnabled" BOOLEAN NOT NULL DEFAULT false,
    "messagingPreference" TEXT NOT NULL DEFAULT 'APP_ONLY',
    "height" INTEGER,
    "bodyType" TEXT,
    "hairColor" TEXT,
    "eyeColor" TEXT,
    "ethnicity" TEXT,
    "bustSize" TEXT,
    "tattoos" TEXT,
    "piercings" TEXT,
    "rate1H" REAL,
    "rate2H" REAL,
    "rateHalfDay" REAL,
    "rateFullDay" REAL,
    "rateOvernight" REAL,
    "currency" TEXT NOT NULL DEFAULT 'CHF',
    "minimumDuration" TEXT,
    "practices" TEXT,
    "orientation" TEXT,
    "acceptedClients" TEXT,
    "outcall" BOOLEAN NOT NULL DEFAULT false,
    "incall" BOOLEAN NOT NULL DEFAULT false,
    "timeSlots" TEXT,
    "availableNow" BOOLEAN NOT NULL DEFAULT false,
    "weekendAvailable" BOOLEAN NOT NULL DEFAULT false,
    "hasPrivatePhotos" BOOLEAN NOT NULL DEFAULT false,
    "hasPrivateVideos" BOOLEAN NOT NULL DEFAULT false,
    "hasWebcamLive" BOOLEAN NOT NULL DEFAULT false,
    "acceptsGifts" BOOLEAN NOT NULL DEFAULT false,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" DATETIME NOT NULL,
    CONSTRAINT "escort_profiles_userId_fkey" FOREIGN KEY ("userId") REFERENCES "users" ("id") ON DELETE CASCADE ON UPDATE CASCADE
);
INSERT INTO "new_escort_profiles" ("availability", "city", "createdAt", "dateOfBirth", "description", "firstName", "galleryPhotos", "id", "languages", "likes", "messagingPreference", "nationality", "profilePhoto", "rates", "rating", "reviewCount", "services", "stageName", "status", "telegramChatId", "telegramConnected", "telegramEnabled", "telegramUsername", "updatedAt", "userId", "verificationData", "videos", "views", "workingArea") SELECT "availability", "city", "createdAt", "dateOfBirth", "description", "firstName", "galleryPhotos", "id", "languages", "likes", "messagingPreference", "nationality", "profilePhoto", "rates", "rating", "reviewCount", "services", "stageName", "status", "telegramChatId", "telegramConnected", "telegramEnabled", "telegramUsername", "updatedAt", "userId", "verificationData", "videos", "views", "workingArea" FROM "escort_profiles";
DROP TABLE "escort_profiles";
ALTER TABLE "new_escort_profiles" RENAME TO "escort_profiles";
CREATE UNIQUE INDEX "escort_profiles_userId_key" ON "escort_profiles"("userId");
PRAGMA foreign_keys=ON;
PRAGMA defer_foreign_keys=OFF;
